name: Spork-Hilite
version: 0.11
abstract: Hilite Code Snippets in Spork
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Spork: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
